Accessing layer and stereo from rawId
pieterdavid/cmssw pull request #9
Opened 2017-06-15 15:54 UTC by alesaggio

2017-06-15 16:14 UTC, OlivierBondu requested changes
Looks good to me! only one minor thing that I can see, I guess the `TIBorTOBparameters.h` cannot be replaced by something already existing in central space ?

2017-06-15 16:14 UTC, OlivierBondu commented on CalibTracker/SiStripLorentzAngle/interface/LA_Filler_Fitter.h
> +#include "DataFormats/SiStripDetId/interface/SiStripDetId.h"
This shouldn't be necessary if the include is already defined in the `TIBorTOBparameters.h` ?

2017-06-15 18:14 UTC, pieterdavid commented on CalibTracker/SiStripLorentzAngle/interface/LA_Filler_Fitter.h
> +#include "DataFormats/SiStripDetId/interface/SiStripDetId.h"
indeed, but it shouldn't be included in `TIBorTOBparameters.h` in the first place, IIRC

2017-06-15 18:15 UTC, pieterdavid commented on CalibTracker/SiStripLorentzAngle/interface/TIBorTOBparameters.h
> +#include "DataFormats/SiStripDetId/interface/SiStripDetId.h"
you don't need this one

2017-06-15 18:15 UTC, pieterdavid commented on CalibTracker/SiStripLorentzAngle/interface/TIBorTOBparameters.h
> +  return ( ((detId.rawId()>>0) & 0x3) == 1 ) ? 1 : 0;
`return (detId.rawId() & 0x3) == 1;` should be sufficient

2017-06-15 18:18 UTC, pieterdavid commented on CalibTracker/SiStripLorentzAngle/interface/TIBorTOBparameters.h
> +// It is used inside CalibTracker/SiStripLorentzAngle only.
How about something like "WARNING: these methods assume that the DetId is a TIBDetId or TOBDetId (and don't check this). Please use the corresponding TrackerTopology methods whenever possible.
Code copied from TIBDetId and TOBDetId.

2017-06-15 18:19 UTC, pieterdavid commented on CalibTracker/SiStripLorentzAngle/src/LA_Filler.cc
> +  unsigned layer = detid.subDetector() == getTIBOrTOBLayer(detid);
should be `unsigned layer = getTIBOrTOBLayer(detid);` (the current code will compare layer do subdetector numbers)

2017-06-15 18:22 UTC, pieterdavid requested changes
A few issues left (one bug, the others minor)

2017-06-15 18:25 UTC, pieterdavid commented
> Looks good to me! only one minor thing that I can see, I guess the TIBorTOBparameters.h cannot be replaced by something already existing in central space ?

Yes, that's what `TIBDetId` and `TOBDetId` were. Since this is essentially a ROOT macro in disguise (all the work is done from the constructor of the `ESProducer`), we don't have a way to access the `edm::EventSetup` without rewriting the whole thing, that's why we'd suggest to add the specific pieces of code here (in such a way that it's not easy to use from elsewhere ;-) ). Actually everything could be moved into the `plugins` directory, nothing depends on `CalibTracker/SiStripLorentzAngle`.
Opinions/thoughts welcome ;-)

2017-06-16 08:27 UTC, OlivierBondu commented on CalibTracker/SiStripLorentzAngle/interface/TIBorTOBparameters.h
> +// It is used inside CalibTracker/SiStripLorentzAngle only.
+1, maybe also specify in which package/subpackage the TIBDetId are, we're going to deprecate them so you want to ease life of people possibly digging history some day...

2017-06-16 08:28 UTC, OlivierBondu approved these changes

2017-06-16 08:49 UTC, pieterdavid commented on CalibTracker/SiStripLorentzAngle/interface/TIBorTOBparameters.h
> +// It is used inside CalibTracker/SiStripLorentzAngle only.
maybe "see `git show CMSSW_9_2_3_patch2:DataFormats/SiStripDetId/interface/TIBDetId.h` and `git show CMSSW_9_2_3_patch2:DataFormats/SiStripDetId/interface/TOBDetId.h`", or is that too detailed?

2017-06-16 08:50 UTC, pieterdavid approved these changes
Looks good now, thanks! As mentioned before: we'll have to explain a bit in the PR why we would go for this solution ;)

2017-06-16 08:51 UTC, OlivierBondu commented on CalibTracker/SiStripLorentzAngle/interface/TIBorTOBparameters.h
> +// It is used inside CalibTracker/SiStripLorentzAngle only.
that sounds perfect :)

2017-06-19 13:59 UTC, OlivierBondu commented
this can be closed if it is outdated by #10 ?

2017-06-20 12:58 UTC, closed without merging